accounts/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import login, logout

app_name = 'accounts'
urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^login/$', login, {'template_name': 'login.html'}, name='login'),
    url(r'^logout$', logout, name='logout'),
    url(r'^signup/$', views.register, name='register'),
    url(r'^(?P<slug>[-\w]+)/$', views.profile, name='profile'),
    url(r'^(?P<slug>[-\w]+)/edit$', views.edit_profile, name='edit_profile'),
    url(r'^(?P<slug>[-\w]+)/change_password$', views.change_password, name='change_password'),

]

home/urls.py
from django.conf.urls import url
from . import views

app_name = 'home'
urlpatterns = [
    url(r'^$', views.allnotes, name='all_notes'),
]

notes/urls.py
from django.contrib import admin
from django.contrib.admin.sites import AdminSite
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('notes/', include('notes_app.urls', namespace='notes')),
    #path('', include('notes_app.urls', namespace='notes')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('ckeditor/', include('ckeditor_uploader.urls')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


AdminSite.site_header = 'Notes Admin Panel'
AdminSite.site_title = 'Notes App Admin'
AdminSite.index_title = 'Welcome to Notes Admin Panel'

notes_app/urls.py
from django.conf.urls import url
from . import views

app_name = 'note_app'
urlpatterns = [
    url(r'^$', views.all_notes, name='all_notes'),
    # url(r'^(?P<id>\d+)$', views.detail, name='note_detail'),
    url(r'^(?P<slug>[-\w]+)/$', views.detail, name='note_detail'),
    url(r'^add$', views.note_add, name='note_add'),
    url(r'^(?P<slug>[-\w]+)/edit$', views.note_edit, name='note_edit'),
    url(r'^(?P<slug>[-\w]+)/delete$', views.note_delete, name='note_delete'),
]

notes_app/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime
from django.utils.text import slugify
from ckeditor.fields import RichTextField
# Create your models here.


class Note(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    slug = models.SlugField(allow_unicode=True, null=True, blank=True)
    content = RichTextField(null=True, blank=True)
    created = models.DateTimeField(blank=True, default=datetime.datetime.now)
    active = models.BooleanField(default=True)
    tags = models.CharField(blank=True, max_length=100)
    img = models.ImageField(upload_to="notes-img", blank=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(Note, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

notes_app/forms.py
from django import forms
from .models import Note
from ckeditor.widgets import CKEditorWidget

class NoteForm(forms.ModelForm):
    content = forms.CharField(widget=CKEditorWidget())
    class Meta:
        model = Note
        fields = ['title','content','tags']

notes_app/views.py
from django.core.checks import messages
from django.shortcuts import render, redirect, get_object_or_404
from .models import Note
from .forms import NoteForm
from django.contrib.auth.models import User
from django.contrib import messages
from accounts.models import ProFile

# Create your views here.


def all_notes(request):
    user = request.user
    all_notes = Note.objects.filter(user = user)
    if request.user.is_authenticated :
        profile = get_object_or_404(ProFile , user = user)
        context = {
            'all_notes' : all_notes ,
            'profile' : profile ,
        }
    else:
        context = {
            'all_notes' : all_notes ,
        }
    return render(request, 'all_notes.html', context)
    # return render(request, 'notes.html', context)


def detail(request, slug):
    note = Note.objects.get(slug = slug)
    if request.user.is_authenticated :
        user = request.user
        profile = get_object_or_404(ProFile , user = user)
        context = {
            'note': note ,
            'profile' : profile ,
        }
    else:
        context = {
            'note': note ,
        }
    return render(request, 'note_detail.html', context)
    # return render(request, 'one_note.html', context)


def note_add(request):
    user = request.user
    profile = get_object_or_404(ProFile , user = user)
    if request.method == 'POST':
        form = NoteForm(request.POST)

        if form.is_valid():
            new_form = form.save(commit=False)
            new_form.user = request.user
            new_form.save()
            messages.success(request, 'Note added successfuly.')
            return redirect('/')
    else:
        form = NoteForm()

    context = {
        'form': form ,
        'profile' : profile ,
    }
    return render(request , 'add.html', context)


def note_edit(request , slug):
    user = request.user
    profile = get_object_or_404(ProFile , user = user)
    note = get_object_or_404(Note, slug = slug)
    if request.method == 'POST':
        form = NoteForm(request.POST , instance = note)
        if form.is_valid():
            new_form = form.save(commit=False)
            new_form.user = request.user
            new_form.save()
            messages.success(request, 'Your Post updated Successfully.')
            return redirect('/notes/' + slug)
    else:
        form = NoteForm(instance = note)

    context = {
        'form' : form ,
        'profile' : profile ,
    }
    return render(request , 'edit.html', context)


def note_delete(request, slug):
    note = get_object_or_404(Note, slug = slug)
    try:
        print (request.method)
        if request.method == 'GET':
            form = NoteForm(request.GET , instance = note)
            note.delete()
            return redirect('/')

    except Exception as e:
        messages.success(request, 'The note could not be deleted : Error {}'.format(e))

notes_app/templates/add.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        {{ form.media }}
        {% buttons %}
            <button type="submit" class="btn btn-primary">Add Note</button>
            <a href="{% url 'notes:all_notes' %}" class="btn btn-primary">Cancel</a>
        {% endbuttons %}
    </form>

{% endblock %}

notes_app/templates/all_notes.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <!--<h3 class="text-danger">All the Available Notes :</h3>-->
    <!--<ul class="list-group list-group-flush">-->
        <!--{% for note in all_notes  %}-->
            <!--<li class="list-group-item list-group-item-action"><a href="{% url 'notes:note_detail' note.slug %}">{{note}}</a></li>-->
        <!--{% endfor %}-->
    <!--</ul>-->

        <!-- Start blog Area -->
        <section class="blog-area section-gap">
                <h3 class="text-white text-center bg-primary">All the Available Notes :</h3>
                <div class="row">
                    {% for note in all_notes  %}
                    <div class="single-blog col-lg-4 col-md-4 border-bottom" style="margin-bottom:20px;margin-top:10px;">
                        {% if note.img %}
                        <a href="{% url 'notes:note_detail' note.slug %}">
                            <img class="f-img img-fluid mx-auto img-thumbnail" src="{{note.img.url}}" alt="">
                        </a>
                        {% else %}
                            <img class="f-img img-fluid mx-auto img-thumbnail" src="{% static 'home-static/img/no_image_available.jpg' %}" alt="">
                        {% endif %}
                        <h4>
                            <a href="{% url 'notes:note_detail' note.slug %}">{{note.title}}</a>
                        </h4>
                        <!--<p class="card-title" style="color:#828a91;">author : {{note.user}} - {{note.created|date:'j M Y'}}</p>-->
                        <div class="bottom d-flex justify-content-between align-items-center flex-wrap" style="background-color:#f4f2f3;">
                            <div>
                                {% comment %} {% if note.img %}
                                    <img class="d-inline-block align-top rounded-circle" src="{{profile.img.url}}"  style="width: 30px; height: 30px;" alt="image profile">
                                {% endif %} {% endcomment %}
                                <img class="img-fluid" src="{% static 'home-static/img/user.png' %}" alt="">
                                <a href="{% url 'accounts:profile' note.user %}"><span>{{note.user.username}}</span></a>
                            </div>
                            <div class="meta">
                                {{note.created|date:'j M Y'}}
                            </div>
                        </div>
                        <p>{{note.content|safe|truncatewords:"30"|linebreaks}}</p>
                        <a class="btn btn-link float-sm-right" href="{% url 'notes:note_detail' note.slug %}">read more</a>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </section>
        <!-- end blog Area -->


{% endblock %}

notes_app/templates/edit.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        {{ form.media }}
        {% buttons %}
            <button type="submit" class="btn btn-primary">Update</button>
            <a href="{% url 'notes:all_notes' %}" class="btn btn-primary">Cancel</a>
        {% endbuttons %}

    </form>

{% endblock %}

notes_app/templates/note_detail.html
{% extends 'base.html' %}

{% block content %}

    <div class="card">
        {# <img src="paris.jpg" class="mx-auto d-block" style="width:50%"> #}
        <h5 class="card-header text-center text-white bg-primary">{{note.title}}</h5>
        <div class="card-body">
            {% if note.img %}
                <img class="mx-auto d-block" style="width:40%;margin:5px;" src="{{note.img.url}}" alt="">
            {% endif %}
            <p class="card-title" style="color:#828a91;">author : {{note.user}} &nbsp;&nbsp;-&nbsp;&nbsp; at : {{note.created}}</p>
            <h5 class="card-text text-justify" style="text-indent: 20px;">{{note.content|safe}}</h5>
            <br><br>
            <p>tags : {{note.tags}}</p>
            <hr>
            {% if note.user.username == user.username %}
                <a href="{% url 'notes:note_edit' note.slug %}" class="btn btn-outline-primary">Edit</a>
                <a href="{% url 'notes:note_delete' note.slug %}" class="btn btn-danger">Delete</a>
            {% endif %}
            <a href="/" class="btn btn-primary" style="float: right;">Go Back</a>
        </div>
    </div>


{% endblock %}

notes_app/templates/notes.html
{% load static %}
<!DOCTYPE html>
<html lang="zxx" class="no-js">
    <head>
        <!-- Mobile Specific Meta -->
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <!-- Favicon-->
        <link rel="shortcut icon" href="{% static 'home-static/img/fav.png' %}">
        <!-- Author Meta -->
        <meta name="author" content="Colorlib">
        <!-- Meta Description -->
        <meta name="description" content="">
        <!-- Meta Keyword -->
        <meta name="keywords" content="">
        <!-- meta character set -->
        <meta charset="UTF-8">
        <!-- Site Title -->
        <title>Quick Notes</title>

        <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,400,300,500,600,700" rel="stylesheet">
        <!--

        CSS
        ============================================= -->
        <link rel="stylesheet" href="{% static 'home-static/css/linearicons.css' %}">
        <link rel="stylesheet" href="{% static 'home-static/css/font-awesome.min.css' %}">
        <link rel="stylesheet" href="{% static 'home-static/css/magnific-popup.css' %}">
        <link rel="stylesheet" href="{% static 'home-static/css/nice-select.css' %}">
        <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
        <link rel="stylesheet" href="{% static 'home-static/css/bootstrap.css' %}">
        <link rel="stylesheet" href="{% static 'home-static/css/main.css' %}">
    </head>

    <body>
        <!-- Start Header Area -->
        <header class="default-header">
            <div class="container">
                <div class="header-wrap">
                    <div class="header-top d-flex justify-content-between align-items-center">
                        <div class="logo">
                            <a href="#home"><img src="{% static 'home-static/img/logo2.png' %}" style="width:28px;" alt="">  Quick Notes</a>
                        </div>
                        <div class="main-menubar d-flex align-items-center">
                            <nav class="hide">
                                <a href="#home">Home</a>
                                <a href="#service">Notes</a>
                                <a href="#appoinment">Login</a>
                                <a href="#consultant">Signup</a>
                            </nav>
                            <div class="menu-bar"><span class="lnr lnr-menu"></span></div>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- End Header Area -->

        <!-- start banner Area -->
        <section class="banner-area relative" id="home">
            <div class="container">
                    <div class="row fullscreen align-items-center justify-content-center">
                        <div class="banner-content col-lg-6 col-md-12">
                            <h1 class="text-uppercase">
                                Create Awesome Notes .. Everywhere
                            </h1>
                            <p>
                                There is something wonderful in writing. We believe it's the ability of words to create emotional, inspiring and thrilling stories.
                            </p>
                            <button class="primary-btn2 mt-20 text-uppercase ">Get Started<span class="lnr lnr-arrow-right"></span></button>
                        </div>
                        <div class="col-lg-6 d-flex align-self-end img-right">
                            <img class="img-fluid" src="{% static 'home-static/img/header-img2.png' %}" alt="">
                        </div>
                    </div>
            </div>
        </section>
        <!-- End banner Area -->

        <!-- Start blog Area -->
        <section class="blog-area section-gap">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-md-8 pb-30 header-text">
                        <h1>Our Recent Notes</h1>
                        <p>
                            Creat , Update , And Share Notes With Others
                        </p>
                    </div>
                </div>
                <div class="row">
                    {% for note in all_notes  %}
                    <div class="single-blog col-lg-4 col-md-4">
                        {% if note.img %}
                            <img class="f-img img-fluid mx-auto" src="{{note.img.url}}" alt="">
                        {% endif %}
                        <h4>
                            <a href="{% url 'notes:note_detail' note.slug %}">{{note.title}}</a>
                        </h4>
                        <p>{{note.content}}</p>
                        <p>tags : {{note.tags}}</p>
                        <div class="bottom d-flex justify-content-between align-items-center flex-wrap">
                            <div>
                                <img class="img-fluid" src="{% static 'home-static/img/user.png' %}" alt="">
                                <a href="#"><span>{{note.user.username}}</span></a>
                            </div>
                            <div class="meta">
                                {{note.created|date:'j M Y'}}
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </section>
        <!-- end blog Area -->

        <!-- start footer Area -->
        <footer class="footer-area section-gap">
            <div class="container">
                <div class="row">
                    <div class="col-lg-2  col-md-6">
                        <div class="single-footer-widget">
                            <h6>Top Products</h6>
                            <ul class="footer-nav">
                                <li><a href="#">Managed Website</a></li>
                                <li><a href="#">Manage Reputation</a></li>
                                <li><a href="#">Power Tools</a></li>
                                <li><a href="#">Marketing Service</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-lg-4  col-md-6">
                        <div class="single-footer-widget mail-chimp">
                            <h6 class="mb-20">Contact Us</h6>
                            <p>
                                56/8, bir uttam qazi nuruzzaman road, west panthapath, kalabagan, Dhanmondi, Dhaka - 1205
                            </p>
                            <h3>012-6532-568-9746</h3>
                            <h3>012-6532-568-97468</h3>
                        </div>
                    </div>
                    <div class="col-lg-6  col-md-12">
                        <div class="single-footer-widget newsletter">
                            <h6>Newsletter</h6>
                            <p>You can trust us. we only send promo offers, not a single spam.</p>
                            <div id="mc_embed_signup">
                                <form target="_blank" novalidate="true" action="https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01" method="get" class="form-inline">

                                    <div class="form-group row" style="width: 100%">
                                        <div class="col-lg-8 col-md-12">
                                            <input name="EMAIL" placeholder="Enter Email" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Email '" required="" type="email">
                                            <div style="position: absolute; left: -5000px;">
                                                <input name="b_36c4fd991d266f23781ded980_aefe40901a" tabindex="-1" value="" type="text">
                                            </div>
                                        </div>

                                        <div class="col-lg-4 col-md-12">
                                            <button class="nw-btn primary-btn">Subscribe<span class="lnr lnr-arrow-right"></span></button>
                                        </div>
                                    </div>
                                    <div class="info"></div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="row footer-bottom d-flex justify-content-between">
                    <p class="col-lg-8 col-sm-12 footer-text m-0">
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    </p>
                    <div class="col-lg-4 col-sm-12 footer-social">
                        <a href="#"><i class="fa fa-facebook"></i></a>
                        <a href="#"><i class="fa fa-twitter"></i></a>
                        <a href="#"><i class="fa fa-dribbble"></i></a>
                        <a href="#"><i class="fa fa-behance"></i></a>
                    </div>
                </div>
            </div>
        </footer>
        <!-- End footer Area -->

        <!-- Start java Script -->
        <script src="{% static 'home-static/js/vendor/jquery-2.2.4.min.js' %}"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
        <script src="{% static 'home-static/js/vendor/bootstrap.min.js' %}"></script>
        <script src="{% static 'home-static/js/jquery.ajaxchimp.min.js' %}"></script>
        <script src="{% static 'home-static/js/jquery.nice-select.min.js' %}"></script>
        <script src="{% static 'home-static/js/jquery.sticky.js' %}"></script>
        <script src="{% static 'home-static/js/parallax.min.js' %}"></script>

        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
        <script src="{% static 'home-static/js/jquery.magnific-popup.min.js' %}"></script>
        <script src="{% static 'home-static/js/waypoints.min.js' %}"></script>
        <script src="{% static 'home-static/js/jquery.counterup.min.js' %}"></script>
        <script src="{% static 'home-static/js/main.js' %}"></script>
        <!-- End java Script -->
    </body>
</html>

notes_app/templates/one_note.html
{% load static %}
<!DOCTYPE html>
<html lang="zxx" class="no-js">
    <head>
        <!-- Mobile Specific Meta -->
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <!-- Favicon-->
        <link rel="shortcut icon" href="{% static 'home-static/img/fav.png' %}">
        <!-- Author Meta -->
        <meta name="author" content="Colorlib">
        <!-- Meta Description -->
        <meta name="description" content="">
        <!-- Meta Keyword -->
        <meta name="keywords" content="">
        <!-- meta character set -->
        <meta charset="UTF-8">
        <!-- Site Title -->
        <title>Quick Notes</title>

        <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,400,300,500,600,700" rel="stylesheet">
        <!--

        CSS
        ============================================= -->
        <link rel="stylesheet" href="{% static 'home-static/css/linearicons.css' %}">
        <link rel="stylesheet" href="{% static 'home-static/css/font-awesome.min.css' %}">
        <link rel="stylesheet" href="{% static 'home-static/css/magnific-popup.css' %}">
        <link rel="stylesheet" href="{% static 'home-static/css/nice-select.css' %}">
        <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
        <link rel="stylesheet" href="{% static 'home-static/css/bootstrap.css' %}">
        <link rel="stylesheet" href="{% static 'home-static/css/main.css' %}">
        <link rel="stylesheet" href="{% static 'home-static/css/mystyle.css' %}">
    </head>

    <body>
        <!-- Start Header Area -->
        <header class="default-header">
            <div class="container">
                <div class="header-wrap">
                    <div class="header-top d-flex justify-content-between align-items-center">
                        <div class="logo">
                            <a href="#home"><img src="{% static 'home-static/img/logo2.png' %}" style="width:28px;" alt="">  Quick Notes</a>
                        </div>
                        <div class="main-menubar d-flex align-items-center">
                            <nav class="hide">
                                <a href="#home">Home</a>
                                <a href="#service">Notes</a>
                                <a href="#appoinment">Login</a>
                                <a href="#consultant">Signup</a>
                            </nav>
                            <div class="menu-bar"><span class="lnr lnr-menu"></span></div>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- End Header Area -->

        <!-- Start blog Area -->
        <section class="blog-area section-gap">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-md-8 pb-30 header-text">
                        <h1>{{note.title}}</h1>
                    </div>
                </div>
                <div class="row">
                    <div class="single-blog col-lg-12 col-md-12">
                        {% if note.img %}
                            <img class="f-img img-fluid mx-auto post_banner" src="{{note.img.url}}" alt="">
                        {% endif %}
                        <p>{{note.content}}</p>
                        <p>tags : {{note.tags}}</p>
                        <div class="bottom d-flex justify-content-between align-items-center flex-wrap">
                            <div>
                                <img class="img-fluid" src="{% static 'home-static/img/user.png' %}" alt="">
                                <a href="#"><span>{{note.user.username}}</span></a>
                            </div>
                            <div class="meta">
                                {{note.created|date:'j M Y'}}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- end blog Area -->

        <!-- start footer Area -->
        <footer class="footer-area section-gap">
            <div class="container">
                <div class="row">
                    <div class="col-lg-2  col-md-6">
                        <div class="single-footer-widget">
                            <h6>Top Products</h6>
                            <ul class="footer-nav">
                                <li><a href="#">Managed Website</a></li>
                                <li><a href="#">Manage Reputation</a></li>
                                <li><a href="#">Power Tools</a></li>
                                <li><a href="#">Marketing Service</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-lg-4  col-md-6">
                        <div class="single-footer-widget mail-chimp">
                            <h6 class="mb-20">Contact Us</h6>
                            <p>
                                56/8, bir uttam qazi nuruzzaman road, west panthapath, kalabagan, Dhanmondi, Dhaka - 1205
                            </p>
                            <h3>012-6532-568-9746</h3>
                            <h3>012-6532-568-97468</h3>
                        </div>
                    </div>
                    <div class="col-lg-6  col-md-12">
                        <div class="single-footer-widget newsletter">
                            <h6>Newsletter</h6>
                            <p>You can trust us. we only send promo offers, not a single spam.</p>
                            <div id="mc_embed_signup">
                                <form target="_blank" novalidate="true" action="https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01" method="get" class="form-inline">

                                    <div class="form-group row" style="width: 100%">
                                        <div class="col-lg-8 col-md-12">
                                            <input name="EMAIL" placeholder="Enter Email" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Email '" required="" type="email">
                                            <div style="position: absolute; left: -5000px;">
                                                <input name="b_36c4fd991d266f23781ded980_aefe40901a" tabindex="-1" value="" type="text">
                                            </div>
                                        </div>

                                        <div class="col-lg-4 col-md-12">
                                            <button class="nw-btn primary-btn">Subscribe<span class="lnr lnr-arrow-right"></span></button>
                                        </div>
                                    </div>
                                    <div class="info"></div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="row footer-bottom d-flex justify-content-between">
                    <p class="col-lg-8 col-sm-12 footer-text m-0">
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    </p>
                    <div class="col-lg-4 col-sm-12 footer-social">
                        <a href="#"><i class="fa fa-facebook"></i></a>
                        <a href="#"><i class="fa fa-twitter"></i></a>
                        <a href="#"><i class="fa fa-dribbble"></i></a>
                        <a href="#"><i class="fa fa-behance"></i></a>
                    </div>
                </div>
            </div>
        </footer>
        <!-- End footer Area -->

        <script src="{% static 'home-static/js/vendor/jquery-2.2.4.min.js' %}"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
        <script src="{% static 'home-static/js/vendor/bootstrap.min.js' %}"></script>
        <script src="{% static 'home-static/js/jquery.ajaxchimp.min.js' %}"></script>
        <script src="{% static 'home-static/js/jquery.nice-select.min.js' %}"></script>
        <script src="{% static 'home-static/js/jquery.sticky.js' %}"></script>
        <script src="{% static 'home-static/js/parallax.min.js' %}"></script>

        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
        <script src="{% static 'home-static/js/jquery.magnific-popup.min.js' %}"></script>
        <script src="{% static 'home-static/js/waypoints.min.js' %}"></script>
        <script src="{% static 'home-static/js/jquery.counterup.min.js' %}"></script>
        <script src="{% static 'home-static/js/main.js' %}"></script>
    </body>
</html>