accounts/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import login, logout

app_name = 'accounts'
urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^login/$', login, {'template_name': 'login.html'}, name='login'),
    url(r'^logout$', logout, name='logout'),
    url(r'^signup/$', views.register, name='register'),
    url(r'^(?P<slug>[-\w]+)/$', views.profile, name='profile'),
    url(r'^(?P<slug>[-\w]+)/edit$', views.edit_profile, name='edit_profile'),
    url(r'^(?P<slug>[-\w]+)/change_password$', views.change_password, name='change_password'),

]

home/urls.py
from django.conf.urls import url
from . import views

app_name = 'home'
urlpatterns = [
    url(r'^$', views.allnotes, name='all_notes'),
]

notes/urls.py
from django.contrib import admin
from django.contrib.admin.sites import AdminSite
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('notes/', include('notes_app.urls', namespace='notes')),
    #path('', include('notes_app.urls', namespace='notes')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('ckeditor/', include('ckeditor_uploader.urls')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


AdminSite.site_header = 'Notes Admin Panel'
AdminSite.site_title = 'Notes App Admin'
AdminSite.index_title = 'Welcome to Notes Admin Panel'

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime
from django.utils.text import slugify
from django.db.models.signals import post_save
# Create your models here.


class ProFile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    slug = models.SlugField(null=True, blank=True)
    headline = models.CharField(blank=True, max_length=100)
    bio = models.TextField(blank=True)
    img = models.ImageField(upload_to="profile-img", blank=True)
    join_data = models.DateTimeField(blank=True, default=datetime.datetime.now)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.user)
        super(ProFile, self).save(*args, **kwargs)

    def __str__(self):
        return '%s' %(self.user)


### signals

def create_profile(sender, **kwargs):
    if kwargs['created']:
        user_profile = ProFile.objects.create(user=kwargs['instance'])

post_save.connect(create_profile,sender=User)

accounts/forms.py
from django import forms
from . import models
from django.contrib.auth.models import User


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = [
            'username' , 'first_name' , 'last_name' , 'email'
        ]


class ProfileForm(forms.ModelForm):
    class Meta:
        model = models.ProFile
        fields = [
            'headline' , 'bio' , 'img'
        ]

accounts/views.py
from django.shortcuts import render , redirect
from django.contrib.auth.forms import UserCreationForm , PasswordChangeForm
from django.contrib.auth import login, authenticate
from .models import ProFile
from django.shortcuts import get_object_or_404
from .forms import UserForm , ProfileForm
from django.contrib import messages

# Create your views here.


def home(request):
    pass


def register(request):
    if request.method =='POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')

            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect('/')
    else:
        form = UserCreationForm
    context = {
        'form' : form ,
    }
    return render(request, 'signup.html', context)



def profile(request, slug):
    # profile = ProFile.objects.get(slug = slug)
    profile = get_object_or_404(ProFile, slug = slug)
    context = {
        'profile' : profile ,
    }
    return render(request , 'profile.html' , context)



def edit_profile(request , slug):
    profile = get_object_or_404(ProFile, slug = slug)
    if request.method == 'POST':
        user_form = UserForm(request.POST , instance=request.user)
        profile_form = ProfileForm(request.POST, request.FILES, instance=profile)

        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'Your Profile updated Successfully.')
            #new_profile.user = request.user
            #profile_form.save()
            return redirect('/accounts/' + slug)
    else:
        user_form = UserForm(instance=request.user)
        profile_form = ProfileForm(instance=profile)

    context = {
        'user_form' : user_form ,
        'profile_form' : profile_form ,
        'profile' : profile ,
    }
    return render(request, 'edit_profile.html' , context)


def change_password(request, slug):
    profile = get_object_or_404(ProFile, slug = slug)
    if request.method == 'POST':
        password_form = PasswordChangeForm(request.user, request.POST)
        if password_form.is_valid():
            password_form.save()
            return redirect('/')
    else:
        password_form = PasswordChangeForm(request.user)

    context = {
        'password_form' : password_form ,
        'profile' : profile ,
    }
    return render(request, 'change_password.html', context)

accounts/templates/change_password.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

    <form method="post">
        {% csrf_token %}
        {% bootstrap_form password_form %}
        {% buttons %}
            <button type="submit" class="btn btn-primary">Save change</button>
        {% endbuttons %}
    </form>

{% endblock %}

accounts/templates/edit_profile.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form user_form %}
        {% bootstrap_form profile_form %}
        {% buttons %}
            <button type="submit" class="btn btn-primary">Save Changes</button>
        {% endbuttons %}
    </form>

{% endblock %}

accounts/templates/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button type="submit" class="btn btn-primary">Login</button>
        {% endbuttons %}
    </form>

{% endblock %}

accounts/templates/profile.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="card text-center" style="width:23rem;margin:0 auto;">
    {% if profile.img %}
        <img class="card-img-top" src="{{profile.img.url}}"  style="width: 50%;margin: 0 auto;margin-top:30px;" alt="image profile">
    {% else %}
        <img class="card-img-top" src="{% static 'home-static/img/avatar-profile.png' %}"  style="width: 50%;margin: 0 auto;margin-top:30px;" alt="image profile">
    {% endif %}
      <div class="card-body">
        <h5 class="card-title text-danger">{{profile.user}}</h5>
        <p class="card-text">Bio : {{profile.bio}}.</p>
      </div>
      <ul class="list-group list-group-flush">
        <li class="list-group-item">Head Line : {{profile.headline}}</li>
        <li class="list-group-item">Join Data : {{profile.join_data}}</li>
      </ul>
      {% if profile.slug == user.username %}
          <div class="card-body bg-light">
            <a href="{% url 'accounts:edit_profile' profile.slug %}" class="btn btn-primary">Edit Profile</a>
            <a href="{% url 'accounts:change_password' profile.slug %}" class="btn btn-primary">Change Password</a>
          </div>
      {% endif %}
</div>

{% endblock %}

accounts/templates/signup.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button type="submit" class="btn btn-primary">Signup</button>
        {% endbuttons %}
    </form>

{% endblock %}