accounts/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import login, logout

app_name = 'accounts'
urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^login/$', login, {'template_name': 'login.html'}, name='login'),
    url(r'^logout$', logout, name='logout'),
    url(r'^signup/$', views.register, name='register'),
    url(r'^(?P<slug>[-\w]+)/$', views.profile, name='profile'),
    url(r'^(?P<slug>[-\w]+)/edit$', views.edit_profile, name='edit_profile'),
    url(r'^(?P<slug>[-\w]+)/change_password$', views.change_password, name='change_password'),

]

home/urls.py
from django.conf.urls import url
from . import views

app_name = 'home'
urlpatterns = [
    url(r'^$', views.allnotes, name='all_notes'),
]

notes/urls.py
from django.contrib import admin
from django.contrib.admin.sites import AdminSite
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('notes/', include('notes_app.urls', namespace='notes')),
    #path('', include('notes_app.urls', namespace='notes')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('ckeditor/', include('ckeditor_uploader.urls')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


AdminSite.site_header = 'Notes Admin Panel'
AdminSite.site_title = 'Notes App Admin'
AdminSite.index_title = 'Welcome to Notes Admin Panel'

notes_app/urls.py
from django.conf.urls import url
from . import views

app_name = 'note_app'
urlpatterns = [
    url(r'^$', views.all_notes, name='all_notes'),
    # url(r'^(?P<id>\d+)$', views.detail, name='note_detail'),
    url(r'^(?P<slug>[-\w]+)/$', views.detail, name='note_detail'),
    url(r'^add$', views.note_add, name='note_add'),
    url(r'^(?P<slug>[-\w]+)/edit$', views.note_edit, name='note_edit'),
    url(r'^(?P<slug>[-\w]+)/delete$', views.note_delete, name='note_delete'),
]

templates/base.html
{% load static %}
{% load bootstrap4 %}
<html>
    <head>
        <title>Welcome in Notes</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- Add CSS library -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'home-static/css/socialmedia.css' %}">
        <!-- Add java script library -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
    </head>

    <body>
        <!-- start Navbar  -->
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary" style="border-bottom: 2px solid black;">
          <a class="navbar-brand" href="/">
            <img src="{% static 'home-static/img/pinterest-logo-brand.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
            Notes App
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                <a class="nav-link" href="http://127.0.0.1:8000/admin/">Admin <span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Dropdown
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="#">Action</a>
                  <a class="dropdown-item" href="#">Another action</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="#">Something else here</a>
                </div>
              </li>
              <li class="nav-item">
                <a class="nav-link disabled" href="#">Disabled</a>
              </li>

            </ul>

            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                    <li class="nav-item dropdown active">
                      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        {% if profile.img %}
                            <img class="d-inline-block align-top rounded-circle" src="{{profile.img.url}}"  style="width: 30px; height: 30px;" alt="image profile">
                        {% endif %}
                            {{user.username}}
                      </a>
                      <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'accounts:profile' user %}">Profile</a>
                        <a class="dropdown-item" href="{% url 'notes:all_notes' %}">My Notes</a>
                        <a class="dropdown-item" href="{% url 'notes:note_add' %}">Add Note</a>
                        <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url 'accounts:logout' %}">Logout<i class="material-icons md-10">arrow forward</i></a>
                      </div>
                    </li>
                {% else %}
                    <li class="nav-item active">
                      <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
                    </li>
                    <li class="nav-item active">
                      <a class="nav-link" href="{% url 'accounts:register' %}">Signup</a>
                    </li>
                {% endif %}
            </ul>

            <form class="form-inline my-2 my-lg-0">
              <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-light my-2 my-sm-0" type="submit">Search</button>
            </form>
          </div>
        </nav>
        <!-- End Navbar  -->

        <!-- Start Header Area -->
        <div class="page-header">
            <div class="alert alert-primary" role="alert">
                <div class="row">
                    <div class="col-sm-3" style="display: flex; flex-direction: row; flex-wrap: wrap; justify-content: center; align-items: center;">
                        <h1 style="font-size:4.3vw;">Welcome in Notes App</h1>
                    </div>
                    <div class="col-sm-9">
                        <img src="{% static 'home-static/img/banner.jpg' %}" class="img-fluid rounded" alt="banner" width="100%" height="70px">
                    </div>
                </div>
            </div>
        </div>
        <!-- End Header Area -->

        <!-- Start Body -->
        <div class="content container-fluid">
            <div class="row">
                <!-- Start Aside Bar -->
                <div class="border-right col-sm-3">
                    <div class="card sidebar" style="width: 100%;">
                      <div class="card-header text-white bg-primary">
                        Featured
                      </div>
                      <ul class="list-group list-group-flush">
                          <a href="#"><li class="list-group-item">Cras justo odio</li></a>
                          <a href="#"><li class="list-group-item">Dapibus ac facilisis in</li></a>
                          <a href="#"><li class="list-group-item">Vestibulum at eros</li></a>
                      </ul>
                    </div>
                    <br>
                    <div class="card sidebar" style="width: 100%;">
                      <div class="card-header text-white bg-primary">
                        Featured
                      </div>
                      <ul class="list-group list-group-flush">
                        <a href="#"><li class="list-group-item">Cras justo odio</li></a>
                        <a href="#"><li class="list-group-item">Dapibus ac facilisis in</li></a>
                        <a href="#"><li class="list-group-item">Vestibulum at eros</li></a>
                      </ul>
                    </div>
                    <br>
                </div>
                <!-- End Aside Bar -->

                <!-- Start Notes -->
                <div class="col-sm-9">

                {% if messages %}
                    <div class="alert alert-success">
                        {% for message in messages %}
                            <strong>Success!</strong> {{ message }}.
                        {% endfor %}
                    </div>
                <!-- <ul class="messages">
                    {% for message in messages %}
                    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                    {% endfor %}
                </ul> -->
                {% endif %}

                {% block content %}
                {% endblock %}
                </div>
                <!-- End Notes -->
            </div>
        </div>
        <!-- End Body -->

        <!-- Footer -->
        <br>
        <footer class="page-footer font-small text-white text-center py-4" style="background-color: #157efb; border-top: 2px solid black;">
            <a href="#" class="fa fa-facebook"></a>
            <a href="#" class="fa fa-twitter"></a>
            <a href="#" class="fa fa-google"></a>
            <a href="#" class="fa fa-youtube"></a>
            <a href="#" class="fa fa-instagram"></a>
            <a href="#" class="fa fa-snapchat-ghost"></a>
            <!-- Copyright -->
            <div class="footer-copyright text-white text-center py-3">© 2018 Copyright:
              <a href="https://mdbootstrap.com/bootstrap-tutorial/" style="color:white"> MDBootstrap.com</a>
            </div>
            <!-- Copyright -->
          </footer>
          <!-- Footer -->
    </body>
</html>